apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: gnugo-as-a-service
spec:
  selector:
    matchLabels:
      app: gnugo
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: gnugo
        tier: backend
    spec:
      containers:
      - name: gnugo-as-a-service
        image: registry-vpc.cn-beijing.aliyuncs.com/shoutan/gnugo-as-a-service:0.4
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: aliyun-registry-secret
